#!/bin/bash

echo "Listening ports:"

netstat -tlnp | awk '$6 == "LISTEN" {print $7}' | sed 's/\/.*//' | sort -u | while read port; do
  pid=$(lsof -i :$port | awk '$1 != "COMMAND" {print $2}')
  program=$(ps -p $pid -o comm=)
  echo "Port $port is being listened to by PID $pid ($program)"
done
