#!/usr/bin/env bash
#Script that displays "Best School" 10 times
end=1
while [ $end -lt 10 ]
do
	if [ $end -eq 4 ]
	then
		echo "bad luck"
	elif [ $end -eq 8 ]
	then
		echo "good luch"
	else
		echo "Best School"
	fi
	end=$((end+1))
done
