#!/usr/bin/env bash
#Script that displays "Best School" 10 times
i=0
j=1
echo "Hour: $i"
i=1
while [ $i -lt 70 ]
do
	echo "$i"
	i=$((i+1))
done
echo "Hour: $j"
while [ $j -lt 12 ]
do
	echo "$j"
	j=$((j+1))
done	
