#!/usr/bin/env bash
#Info about school
file_n="school"
if [ -e $file_n ]
then
	echo "school file exists"
	if [ -s $file_n ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f $file_n ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
