#!/usr/bin/env bash

# Get list of network interfaces
interfaces=$(ip -o link show | awk -F': ' '{print $2}')

# Loop through each interface and get its IPv4 address
for interface in $interfaces; do
    ip_address=$(ip -4 addr show $interface | grep -oP '(?<=inet\s)\d+(\.\d+){3}')
    if [[ ! -z "$ip_address" ]]; then
        echo "$interface: $ip_address"
    fi
done
